version: 2

project_name: file-counter

before:
  hooks:
    # Tidy
    - go mod tidy
    # Generate
    - go generate ./...

builds:
  - id: file-counter-windows
    main: ./app/cmd/counter/file-counter.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags: -s -w

  - id: file-counter-linux
    main: ./app/cmd/counter/file-counter.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags: -s -w

  - id: file-counter-macos
    main: ./app/cmd/counter/file-counter.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    ldflags: -s -w

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}MacOs
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
