name: testing

on:
  pull_request:
  push:
    branches: [master]
    tags-ignore: "*"

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install depednecies
        run: go mod download

      - name: Run tests
        run: go test -coverprofile=unit.coverage.out ./...

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./unit.coverage.out
          fail_ci_if_error: false
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: unit.coverage.out         
      
